spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/review_app_db'
    username: postgres
    password: mduck
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
        type.desciptor.sql.BasicBinder: TRACE
token:
  access:
    salt: 'access-salt'
    duration: 30000 # 30s
  refresh:
    salt: 'refresh-salt'
    duration: 2592000000 # 30 days